//permanent
const CHANGE_PERMANENT = 'CHANGE_PERMANENT';
const ADD_PURCHASE = 'ADD_PURCHASE';
const DELETE_FROM_PURCHASES = 'DELETE_FROM_PURCHASES';

//temporary
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const CHANGE_TEMPORARY = 'CHANGE_TEMPORARY';

export {
  CHANGE_PERMANENT,
  ADD_PURCHASE,
  DELETE_FROM_PURCHASES,
  ADD_PRODUCTS,
  UPDATE_PRODUCT,
  CHANGE_TEMPORARY,
};
